### ISSUE TITLE
problem occurs when running the DeepMimic.py

### ISSUE THREAD

**Issue by jxwjasonborne** [xbpeng/DeepMimic#10]
Hi, peng !  Thank you very much for releasing the code and it is a great work.
I followed the instructions and generated DeepMimicCore.py successfully.
then I run the command "python3 DeepMimic.py --arg_file args/kin_char_args.txt" , it produced the result:
**"
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: (nil)
[ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f67aba3d390]
"**
On the other hand, I run the command "python3 mpi_run.py --arg_file args/train_humanoid3d_spinkick_args.txt --num_workers 4" and it worked well and began the training process.

I check the related code, and guess that  "enable_draw " in the  "world = build_world(args, enable_draw=True)" maybe affect the bug. 

thank  you very much.

**Comment by jxwjasonborne** [comment]
PS: I use Python3.5 to Makefile in the Ubuntu16.04. I don't know whether it has the effect on running successfully.

**Comment by jxwjasonborne** [comment]
@dev-bz thx for your help. I comment this line and re-compile in the DeepMimicCore, but the bug still exists. 
I guess does this problem relate to the OpenMPI and OpenGL ? thx.

**Comment by dev-bz** [comment]
in Deepmimic.py #glutInitContextVersion(3, 2)

**Comment by dev-bz** [comment]
My computer does not seem to support this version of the GL API, so I do not let it specify the GL version, so that it is in default.

**Comment by jxwjasonborne** [comment]
@dev-bz thx very much ! I comment that line and it worked ! 
btw, could you explain the reason that cause this bug, since I'm not familiar with rendering.
thx.

**Comment by dev-bz** [comment]
if keep that line work, glGenVertexArrays(1, &mVaoID) will fail in RenderState.h just on some machine. (bad english!!!)

**Comment by jxwjasonborne** [comment]
@dev-bz thank you very much!

**Comment by Superlee506** [comment]
@dev-bz @jxwjasonborne  Hi, thanks for this related issue and I face the same problem.
I commented the glutInitContextVersion(3, 2) in[ Line 269](https://github.com/xbpeng/DeepMimic/blob/master/DeepMimic.py#L269), but the bug still exists. Do I need to do some other modifications?
