### ISSUE TITLE
Statistics won't be logged to output folder while trianing

### ISSUE THREAD

**Issue by SuperTardigrade** [xbpeng/DeepMimic#101]
Hi,
I'm trying to train a policy with mpi_run.py. It seems to run correctly (statistics are printed out regularly) but only the first iteration is saved log file in /output. Any idea how to solve this issue ?
Thank you in advance

**Comment by Zju-George** [comment]
Hello!

**Comment by SuperTardigrade** [comment]
Okay actually it updates every 200 iterations
