### ISSUE TITLE
Processes run on only one CPU during training

### ISSUE THREAD

**Issue by SuperTardigrade** [xbpeng/DeepMimic#102]
Hi,
I'm trying to run this command on a 16-cores Ubuntu 16.04 LTS :
`python mpi_run.py --arg_file args/train_humanoid3d_run_args.txt --num_workers 16`
It does divide the running into 16 processes but they all run on one single CPU and I would like them to run on all CPUs instead. Can anyone help ?
![mon_issue](https://user-images.githubusercontent.com/40835337/72366083-d9612380-36f9-11ea-811f-a9fd49cba63c.jpeg)

**Comment by SuperTardigrade** [comment]
I figured it out actually. One solution is to bind each process to a CPU after starting the execution. To do this, you can use this command :
`taskset -pc [CPU number] [process ID]`
for example :
`taskset -pc 2 3039`
You can find more details about how to assign a process to a CPU on  [https://www.hecticgeek.com/2012/03/assign-process-cpu-ubuntu-linux/](this website)

**Comment by xbpeng** [comment]
Cool, thanks for the tip!

**Comment by luosh18** [comment]
adding `--bind-to hwthread` to [line 18 of mpi_run.py](https://github.com/xbpeng/DeepMimic/blob/master/mpi_run.py#L18) :
`cmd = 'mpiexec -n {:d} --bind-to hwthread python3 DeepMimic_Optimizer.py '.format(num_workers)`
can fix this issue easier
ref: [mpiexec man page](https://www.open-mpi.org/doc/v4.1/man1/mpiexec.1.php)
