### ISSUE TITLE
what is the EXP_ACTION_FLAG used for?

### ISSUE THREAD

**Issue by Steven89Liu** [xbpeng/DeepMimic#105]
it seems that the EXP_ACTION_FLAG is used to filter some actions depending on the exp_params_curr.rate, but i don't know why.  thanks.

**Comment by xbpeng** [comment]
This is trick to avoid adding exploration at every step, which can cause the character to be too jittering. What we do instead, is we only add noise with some epsilon probability at every timestep. EXP_ACTION_FLAG indicates if exploration noise was added to the action in that step, since only actions that was the result of exp noise can be used to compute the policy gradient.

**Comment by Steven89Liu** [comment]
thanks for you reply so quickly. 
why only part of the actions are used to compute the policy gradient but all the actions are used for critic? also Could you tell me the difference between the **self.norm_a_std_tf** and **self.a_norm.std_tf** i have been wondering for a long time? why self.norm_a_std_tf is used in the TFUtil.calc_logp_gaussian instead of the self.a_norm.std_tf? thanks very much.

**Comment by xbpeng** [comment]
updating the critic using all state is still ok, it just means that it's learning the value function for a mixture of a stochastic and deterministic policy. But for updating the actor, the policy gradient can only be computed using samples from the stochastic policy.

self.norm_a_std_tf is the standard deviation of the normalized action distribution. self.a_norm.std_tf is the standard deviation of the normalizer used only to normalize actions. It is NOT the standard deviation of the action distribution. All updates are performed in the normalized spaces.

**Comment by Steven89Liu** [comment]
thanks.
by default setting, the self.norm_a_std_tf is a fixed value for **all the states** while the actor network is used to caculate the mean of action distribution **for some state**.  but from the calling of **TFUtil.calc_logp_gaussian(norm_tar_a_tf, self._norm_a_mean_tf, self.norm_a_std_tf)**, the a_mean_tf seems more like a mean of action distribution for **all the states**.  which one is right? thanks.

**Comment by xbpeng** [comment]
Yes, the standard deviation for the action distribution is fixed for all states. But a_mean_tf is the mean of the action distribution for each state, which can vary between states. The call to calc_logp_gaussian will calculate the logp for each state separately.

**Comment by Steven89Liu** [comment]
thanks.
