### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by lordNil** [xbpeng/DeepMimic#115]
When trying to run they python files for deep mimic, I get a syntax error
It seems to be thinking the print function is a native python function. 
`
    Logger.print('Shutting down...')
               ^
SyntaxError: invalid syntax
`
Also, I have the issue of:
`
 from . import _DeepMimicCore
ImportError: libGLEW.so.2.1: cannot open shared object file: No such file or directory
`
You have posted a solution to this, but I am not sure how to implement it. Can you help explain how to resolve this error?

**Comment by xbpeng** [comment]
I've seen that print issue before, when running with python2. Running with python3 should fix that.

For the libGLEW error, it probably can't find libGLEW.so. It might be located somewhere else. Take a look at where the lib file is, and add the directory to the makefile.

**Comment by lordNil** [comment]
I can find libGLEW.so and it is in /usr/lib64, but how do I add the directory to the makefile? ( I assume the makefile in Deepmimic Core). 

Do I use GLEW_DIR = /usr/lib64

**Comment by lordNil** [comment]
I fixed it, 
I ran this in terminal:
sudo ldconfig /usr/lib64
to make sure that the program can look in /usr/lib64
You may want to add this instruction, as I am installing on a new Ubuntu OS, and this problem will appear for many people.
