### ISSUE TITLE
Where can I get Dog's mocap data

### ISSUE THREAD

**Issue by YuZhang10** [xbpeng/DeepMimic#117]
Hi, I notice deepmimic supports several dog's gaits such as canter, pace and trot
![image](https://user-images.githubusercontent.com/30391848/80450262-bd555b00-8953-11ea-8c61-11bdc7e5eed4.png)

I wonder where did you get these mocap data?

I have searched in :
- http://mocap.cs.sfu.ca/ 
- http://mocap.cs.cmu.edu/

but they both only has human mocap data. 

Thanks in advance!

**Comment by xbpeng** [comment]
the dog mocap data is from here
https://github.com/sebastianstarke/AI4Animation

**Comment by YuZhang10** [comment]
Wow! Thanks for your timely reply.
It helps a lot! 👍
