### ISSUE TITLE
Weights for imitation reward computation

### ISSUE THREAD

**Issue by NoctisZ** [xbpeng/DeepMimic#124]
Hi, thank you so much for this wonderful work! I successfully run the model using the original configuration and want to train using a new mocap motion. To do so I wish to change the weights for computing imitation reward (e.g. w_p, w_v, w_e ad w_c) in the paper, but couldn't locate them in the code. It would be great if you can let me know where they are so I may adjust them, appreciate it.

**Comment by xbpeng** [comment]
The weights are here:
https://github.com/xbpeng/DeepMimic/blob/c0731625e72c96a3f758def75f5e4ecbf60e8ca1/DeepMimicCore/scenes/SceneImitate.cpp#L9
You can modify `pose_w`, `vel_w`, etc..

**Comment by NoctisZ** [comment]
Found them, thank you for the timely response!
