### ISSUE TITLE
Error in Build wrapper 

### ISSUE THREAD

**Issue by nayariml** [xbpeng/DeepMimic#137]
Hi, I have the issue below when I try to build wrapper, "make python":

.................
~/DeepMimic-master/DeepMimicCore$ make python
clang++ -c -g -std=c++11 -O3 -Wall -fPIC  -I./ -I../../libraries/eigen -I../../libraries/bullet3/src -o objs/sim/ExpPDController.o sim/ExpPDController.cpp
In file included from sim/ExpPDController.cpp:1:
In file included from sim/ExpPDController.h:3:
In file included from ./sim/PDController.h:5:
In file included from ./sim/SimBodyJoint.h:3:
In file included from sim/SimBodyLink.h:3:
In file included from ./sim/SimObj.h:4:
./sim/World.h:5:10: fatal error: 'btBulletDynamicsCommon.h' file not found
#include "btBulletDynamicsCommon.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:49: objs/sim/ExpPDController.o] Error 1

...........
Inside of "Makefile" I think there are the right local of dir because have this file "btBulletDynamicsCommon.h"
in this directory.

EIGEN_DIR = /usr/local/include/eigen3
BULLET_INC_DIR = /usr/local/include/bullet

I also make sure the bullet is correctly installed on my computer.
Can you help me?

Thanks.

**Comment by xbpeng** [comment]
It does look like it's having trouble finding the bullet files. But it's a bit hard to tell what might be going wrong just from the printout here. Maybe see if anyone else has other suggestions.

**Comment by nayariml** [comment]
It works now. I had some problems editing the make file. Anyway, thanks for the answer.

**Comment by shruty808** [comment]
hii nayaramL , cam you tell me what changes to made to make file. I am facing the same problem

**Comment by xiaoyang-RL9** [comment]
add  /bullet/src is ok
