### ISSUE TITLE
X Error of failed request: BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by fcossio** [xbpeng/DeepMimic#147]
After installing and compiling, I'm trying to run the first example in the HOW TO USE section.
```
python DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt
```

but it breaks without much detail:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  43
  Current serial number in output stream:  44
```
Does anyone know how to solve this?

**Comment by fcossio** [comment]
I don't know what was wrong but restarting the computer after installing everything made it work

**Comment by YIN-Tairan** [comment]
I had the same error and it's solved in exactly the same way. Thanks for the sharing.
