### ISSUE TITLE
Humanoid character ROS compatable URDF 

### ISSUE THREAD

**Issue by EricVoll** [xbpeng/DeepMimic#151]
Hi, 
Just letting you (and others) know that I worked on a urdf of your humanoid with ROS-urdf-compatible joints. This means converting the spherical joints to three revolute joints and converting the motions files accordingly.

In [this repo](https://github.com/EricVoll/amp_motion_conversion) you can find the code, urdf/xacro & motion files, and some quick instructions. 

I'll close this issue since its only for others to find in the future.

**Comment by xbpeng** [comment]
awesome, thanks a lot for sharing that!
