### ISSUE TITLE
'run_amp_heading_getup_humanoid3d_locomotion_getup_args' doesn't works as expected.

### ISSUE THREAD

**Issue by AGPX** [xbpeng/DeepMimic#155]
Hi,

I have tried the scene 'run_amp_heading_getup_humanoid3d_locomotion_getup_args.txt', but it doesn't seems to work as expected, there is some special reason (it runs instead of walking when it is close to the goal and therefore this cannot be reached)? Here a recorded video:

[Video](https://youtu.be/XTSH7mwRDkc)

Thanks.

**Comment by xbpeng** [comment]
This is training the target heading task, not the target location task. The target heading task just has the character following the direction of the green arrow, the character is not trained to move to a target location. The target location you see in the visualizer is just there for the user to control the target direction. If you want to train the character to perform the target location task, using run_amp_target_humanoid3d_locomotion_args.txt.

**Comment by AGPX** [comment]
Ah ok, thanks.
