### ISSUE TITLE
freeglut error

### ISSUE THREAD

**Issue by bssrdf** [xbpeng/DeepMimic#16]
Hi I have successfully built the python wrapper with VS2017.
When I run 
python DeepMimic.py --arg_file args\run_humanoid3d_spinkick_args.txt

I got the following output. Please help, thanks

OpenGL_accelerate seems to be installed, but unable to import expected wrapper entry points!
O:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From O:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
O:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\fastparquet\dataframe.py:7: FutureWarning: 'pandas.core' is private. Use 'pandas.Categorical'
  from pandas.core.categorical import Categorical, CategoricalDtype
Renderer: GeForce GT 730/PCIe/SSE2
OpenGL version supported 3.2.0 NVIDIA 416.34
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/VertColor_PS.glsl
Compiling shader: data/shaders/FullScreenQuad_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl

Agent Registry
Num Agents: 1
Agent 0: ct_pd

Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/Depth_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/Lighting_Lambert_PS.glsl
Loaded scene: Imitate

Num Agents: 1
Agent 0: data/agents/ct_agent_humanoid_ppo.txt
2018-10-20 01:54:18.955724: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Built actor net: fc_2layers_1024units
Built critic net: fc_2layers_1024units
{
"ID": 0,
 "Type": "PPO",
 "ActionSpace": "Continuous",
 "StateDim": 197,
 "GoalDim": 0,
 "ActionDim": 36
}
Model loaded from: data/policies/humanoid3d/humanoid3d_spinkick.ckpt

freeglut  ERROR:  Function \<glutPostRedisplay\> called without first calling 'glutInit'.

**Comment by bssrdf** [comment]
Thanks for reply. 
I did a bit digging. The only two places where glutInit gets called are
void cDrawUtil::InitOffscreenDrawContext()
 and 
void InitDraw(int argc, char** argv)

But both functions seem not being called by python via DeepMimicCore. I put prints in both functions and neither print showed up. Shouldn't one of them be called somewhere down the process?

**Comment by bssrdf** [comment]
Now I have more clues as to the problem. The line failed in DeepMimic.py is
 world.env.reshape(win_width, win_height)  which is in fact a call to  cDeepMimicCore::Reshape(int w, int h) whose glutPostRedisplay() gets complain from freeglut. I thought all glut calls in DeepMimicCore should use context established by pyOpengl. Am I missing something?

As a hack, I added 
InitOffscreenDrawContext();
into 
void cDrawUtil::InitDrawUtil() after
glewInit();

after this change, freeglut isn't complaining any more. But I got a black screen.

**Comment by bssrdf** [comment]
Ok, I solved the problem by commenting out `glutPostRedisplay()` call in function 
`void cDeepMimicCore::Reshape(int w, int h)`
Not sure the consequence of this change. 
Both tests run fine now.

**Comment by xbpeng** [comment]
i think getting rid of the redisplay call in reshape is probably ok. It just means that the rendering won't refresh as promptly when reshaping the windows, which should be a fairly minor inconvenience.

**Comment by bssrdf** [comment]
I found it puzzling that any call to glut within DeepMimicCore will cause freeglut to complain with glutInit error. Here is another case: right click while dragging the mouse (pan the camera) will crash with the same error.  This time it is the glutGetModifiers() call in cCamera:: MouseMove().  Again the solution is to disable glut call. I have to pass modifier key via python interface and this involves modifying several files. 

I don't know whether the problem is specific to my system environment (Win10, VS 2017, Winpython 3.6, freeglut 3.0.0) or not.  If anyone encounters this, I could submit a PR with this fix. 

Thanks for the help and discussion. Nice work and appreciated the code sharing. 

BTW, any plan to release the SFV code?

**Comment by xbpeng** [comment]
we haven't decided on a code release for SFV yet.

**Comment by GarrettZhen** [comment]
> I found it puzzling that any call to glut within DeepMimicCore will cause freeglut to complain with glutInit error. Here is another case: right click while dragging the mouse (pan the camera) will crash with the same error. This time it is the glutGetModifiers() call in cCamera:: MouseMove(). Again the solution is to disable glut call. I have to pass modifier key via python interface and this involves modifying several files.
> 
> I don't know whether the problem is specific to my system environment (Win10, VS 2017, Winpython 3.6, freeglut 3.0.0) or not. If anyone encounters this, I could submit a PR.
> 
> Thanks for the help and discussion. Nice work and appreciated the code sharing.
> 
> BTW, any plan to release the SFV code?

Excuse me, I also met some problems about glutInit error. When I run the DeepMimic.py, the error will come that OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling. How to solve it? Thanks！（PS：看起来老哥像是自己人，能帮忙说一下怎么解决吗？谢谢）

**Comment by GarrettZhen** [comment]
Excuse me, I met the same problem. I want to know where "void cDeepMimicCore::Reshape(int w, int h)" is. Thanks!!! My environment is Windows10, Visual studio 2015. python 3.5.4.(PS：看起来老哥像是自己人，能帮忙说一下怎么解决吗？谢谢）

> Ok, I solved the problem by commenting out `glutPostRedisplay()` call in function
> `void cDeepMimicCore::Reshape(int w, int h)`
> Not sure the consequence of this change.
> Both tests run fine now.

Excuse me, I met the same problem. I want to know where "void cDeepMimicCore::Reshape(int w, int h)" is. Thanks!!! My environment is Windows10, Visual studio 2015. python 3.5.4.(PS：看起来老哥像是自己人，能帮忙说一下怎么解决吗？谢谢）
