### ISSUE TITLE
VS Build error, 'M_PI': undeclared identifier, and other strange error

### ISSUE THREAD

**Issue by Frank-Li-Code** [xbpeng/DeepMimic#17]
Greetings friend, I don't know why I get all those error, can you help me with it? VS version I use is Visual Studio Community 2017, MSbuild version is 15.0;
if you don't have time, please at least tell me what tool you use to build DeepMimicCore. thank you
![e_0](https://user-images.githubusercontent.com/43923352/47263950-4a894980-d53e-11e8-8c03-a74e37259a7b.PNG)
![e_1](https://user-images.githubusercontent.com/43923352/47263951-4b21e000-d53e-11e8-9058-fbb004b1cd48.PNG)
![w_0](https://user-images.githubusercontent.com/43923352/47263952-4b21e000-d53e-11e8-9813-095f6b5346e0.PNG)
![w_1](https://user-images.githubusercontent.com/43923352/47263953-4bba7680-d53e-11e8-86c8-4d6e38c3a8bd.PNG)
![w_2](https://user-images.githubusercontent.com/43923352/47263954-4bba7680-d53e-11e8-90f8-e80dc44904c6.PNG)
![w_3](https://user-images.githubusercontent.com/43923352/47263955-4bba7680-d53e-11e8-9bde-07e5f8af184a.PNG)
![w_4](https://user-images.githubusercontent.com/43923352/47263956-4c530d00-d53e-11e8-9e61-a96b88077d7b.PNG)
And I was just curious, why won't you just use pybullet instead rewrite all environment by youself ?

**Comment by bssrdf** [comment]
I got the same build error using VS2017. You may add the following at the beginning of MathUtil.h. to make it work.
```
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
```
