### ISSUE TITLE
The construction of the motion clips for AMP.

### ISSUE THREAD

**Issue by Frank-Dz** [xbpeng/DeepMimic#176]
Hi~ Thank you so much for your great work.
May I know if it is possible to provide the correspondence between the motion file in this codebase and the original name (.fbx or .bvh file) in the dataset?
For example, the humanoid3d_run.txt may correspond to the CMU 07_01_cmu.fbx?

Thank you very much!

**Comment by xbpeng** [comment]
sorry but it's been too long, i don't have the original source motions for each of the motion clips recorded somewhere

**Comment by Frank-Dz** [comment]
> sorry but it's been too long, i don't have the original source motions for each of the motion clips recorded somewhere

No problem! Thanks!
I have another question, I am trying to train an AMP model to mimic (no task reward) a rolling behavior on Isaacgym. But it is very hard for the model to mimic the rolling even with low GP. Any suggestions on this? 

Thank you very much!
![image](https://user-images.githubusercontent.com/55009565/181208754-86435ae7-a40d-46fc-8b95-f831ea751f60.png)

![image](https://user-images.githubusercontent.com/55009565/181208681-02cf6ab2-6351-4037-b5ac-bab8e1d4a718.png)

**Comment by Frank-Dz** [comment]
> > sorry but it's been too long, i don't have the original source motions for each of the motion clips recorded somewhere
> 
> No problem! Thanks! I have another question, I am trying to train an AMP model to mimic (no task reward) a rolling behavior on Isaacgym. But it is very hard for the model to mimic the rolling even with low GP. Any suggestions on this?
> 
> Thank you very much! ![image](https://user-images.githubusercontent.com/55009565/181208754-86435ae7-a40d-46fc-8b95-f831ea751f60.png)
> 
> ![image](https://user-images.githubusercontent.com/55009565/181208681-02cf6ab2-6351-4037-b5ac-bab8e1d4a718.png)
> 
> The model should learn to run and roll forward.

Hi~Jason @xbpeng I finally made it!
Thanks!

**Comment by xbpeng** [comment]
cool, glad to hear you got it to work! For rolling, make sure to disable to early termination for contacts.

**Comment by Frank-Dz** [comment]
Thanks! I stopped the early termination. The  problem was caused by my own
reference motion processing part.

Thanks again!
