### ISSUE TITLE
How to train the controller for new character and terrain

### ISSUE THREAD

**Issue by jxwjasonborne** [xbpeng/DeepMimic#18]
@xbpeng How to train the controller for new character and terrain using other motion data clips ?
 Related files are in the ./Data file, but where to find new character and terrain files ? And how to process data to make it available for network inputs ?

Thank you very much !

**Comment by xbpeng** [comment]
We've only released the humanoid character and we haven't included irregular terrain for this release. Sorry about that. To use your own mocap clips, take a look at the mocap section of the readme.

**Comment by jxwjasonborne** [comment]
@xbpeng thank you very much for your reply.
