### ISSUE TITLE
What are the time_lim arguments to mpi_run.py?

### ISSUE THREAD

**Issue by ajlangley** [xbpeng/DeepMimic#183]
What do the following arguments mean?

--time_lim_min 
--time_lim_max 
--time_lim_exp 
--time_end_lim_min
--time_end_lim_max
--time_end_lim_exp

Thanks for the help!

**Comment by xbpeng** [comment]
We sometimes train using a curriculum, where we start with short episodes and then progressively make the episodes longer as training processes. time_lim_min and time_lim_max define the starting range for the episode lengths. The episode length will be sampled between [min, max]. Similarly time_end_lim_min and time_end_lim_max is the episode lengths at the later stage of training. These values are annealed between the start and end values over a number of samples defined by (anneal_samples). You can ignore the lim_exp parameters.

**Comment by ajlangley** [comment]
Great, that clears it up. Thanks so much for the quick response!
