### ISSUE TITLE
Question About deepmimic

### ISSUE THREAD

**Issue by tanakataiki4** [xbpeng/DeepMimic#24]
Thanks for a great repo!
I'd like to ask a few question about a things that was hard to figureout from code and a bit hard the constract enviroment.
1. Did you penalize at the ground contact of any body except foot other than termination?

2. About the Skill selector 
Is the skill selection done at the reset phase and maximum number of step is shorter than single skills such as one action? Because if the initial pose is the same in a few skill reference motion then  it's equal to do the action in the middle of action. Also the collected states includes the phase variable therefore the first step should be multiple of each action's step.

**Comment by xbpeng** [comment]
1. in addition to terminating the episode whenever there is unwanted ground contact, the agent also receives a reward of zero for that step.

2. Yes, we only select a new skill at the start of every cycle when the phase resets.
