### ISSUE TITLE
problem occurs when running the DeepMimic.py 

### ISSUE THREAD

**Issue by Superlee506** [xbpeng/DeepMimic#29]
Hi, 
"
*** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: (nil)
[ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f67aba3d390]
"
On the other hand, I run the command "python3 mpi_run.py --arg_file args/train_humanoid3d_spinkick_args.txt --num_workers 4" and it worked well and began the training process.

The same bug occurs as in [issue#10](https://github.com/xbpeng/DeepMimic/issues/10), and I commented the " glutInitContextVersion(3, 2)" in DeepMimic.py. But the bug still exists, Do I need some extra modifications?

**Comment by Superlee506** [comment]
It has been solved. Pay attention to your nvidia driver.

**Comment by dev-bz** [comment]
check DeepmimicCore/Main.cpp:InitDraw()

**Comment by kyanome** [comment]
I have a same problem. Could you please tell me how to solve the problem? 

When an error happened, which nvidia driver did you use? In addition, which nvidia driver did you change it into to solve an error?

thank you so much.

**Comment by jaeha1223** [comment]
comment 'glutInitContextVersion(3, 2)' line in DeepMimic.py
This error occurred by opengl version conflict.

**Comment by asawaswapnil** [comment]
How can I check for the driver needed? Do u need Nvidea even to run python DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt? I need to run the pre-trained model on Intel® UHD Graphics 620 (Kabylake GT2). Can I do that? Is there any way I can modify the code to do that?

**Comment by tuchapong1234** [comment]
> It has been solved. Pay attention to your nvidia driver.

It happen to my computer too but from [issue#10](https://github.com/xbpeng/DeepMimic/issues/10) I have forward to file DeepMimic.py and it doesn't contain 'glutInitContextVersion(3, 2)'. 

Please help about the nvidia driver what would have caused the problem. I am using OpenGL version string: 4.6.0 NVIDIA 555.42.06 [NVIDIA GeForce RTX 4070 Ti SUPER]
