### ISSUE TITLE
 Signal: Bus error (7) problem occurs when running the DeepMimic.py

### ISSUE THREAD

**Issue by kyanome** [xbpeng/DeepMimic#30]
Hi! When I run Deepmimic.py, the following error occurred. 

**Renderer: GeForce GTX 1080/PCIe/SSE2
OpenGL version supported 3.2.0 NVIDIA 396.26
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/VertColor_PS.glsl
Compiling shader: data/shaders/FullScreenQuad_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
 *** Process received signal ***
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: (nil)
 [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f31138b8390]
 *** End of error message ***
Segmentation fault (core dumped)**

So, I check [issue#10](https://github.com/xbpeng/DeepMimic/issues/10), and I comment out " glutInitContextVersion(3, 2)" in DeepMimic.py and Main.cpp. But error stills occurs. 

**Renderer: GeForce GTX 1080/PCIe/SSE2
OpenGL version supported 4.6.0 NVIDIA 396.26
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/VertColor_PS.glsl
Compiling shader: data/shaders/FullScreenQuad_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
*** Process received signal ***
Signal: Bus error (7)
Signal code:  (128)
Failing at address: (nil)**

How Do I modify the code ? Thank you very much.

# Dependency
Python 3.5.2
Ubuntu16.04

**Comment by xbpeng** [comment]
it's hard to tell what the issue is just from that error message. Can you locate which line of code is causing that?

**Comment by kyanome** [comment]
I solved this problem to change NVIDIA 396.26 to NVIDIA 390.87.
Thank you so much.

**Comment by kyanome** [comment]
I solved this problem to change NVIDIA 396.26 to NVIDIA 390.87.
Thank you so much.

**Comment by xbpeng** [comment]
cool, good to hear

**Comment by wangyuwei2015** [comment]
Hi, I encounter the same problem but I am using GTX1070 with the driver version of Nvidia 384.130.

Renderer: GeForce GTX 1070/PCIe/SSE2
OpenGL version supported 4.5.0 NVIDIA 384.130
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/VertColor_PS.glsl
Compiling shader: data/shaders/FullScreenQuad_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
[yd:11928] *** Process received signal ***
[yd:11928] Signal: Bus error (7)
[yd:11928] Signal code:  (128)
[yd:11928] Failing at address: (nil)

Could you tell me how to find the specific version of driver for your graphic card?

**Comment by kyanome** [comment]
I referred to my friend's way. He solved Segmentation fault problem using Nvidia 391.35 on Windows. 
So, I decided not to use driver that is higher than 391,  I have used NVIDIA 390.87.

**Comment by zfwang615** [comment]
@wangyuwei2015 
Hi! Have you ever solve your problem? I have a same problem but I am using GeForce GT650M with the driver version of Nvidia 384.130.

Renderer: GeForce GT 650M/PCIe/SSE2
OpenGL version supported 4.5.0 NVIDIA 384.130
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/VertColor_PS.glsl
Compiling shader: data/shaders/FullScreenQuad_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
[zfwang:09980] *** Process received signal ***
[zfwang:09980] Signal: Bus error (7)
[zfwang:09980] Signal code:  (128)
[zfwang:09980] Failing at address: (nil)

Look forward to your kind reply.

**Comment by bsivanantham** [comment]
@xbpeng @kyanome 
Hi, I having below problem . Please guide me where i am going wrong 

*```
*DeepMimic.py --arg_file args/run_humanoid3d_dance_a_args.txt
Successfully to load args from: args/run_humanoid3d_dance_a_args.txt
Renderer: GeForce GTX 970/PCIe/SSE2
OpenGL version supported 4.6.0 NVIDIA 390.87
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/VertColor_PS.glsl
Compiling shader: data/shaders/FullScreenQuad_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
Compiling shader: data/shaders/Mesh_VS.glsl
Compiling shader: data/shaders/DownSample_PS.glsl
scene imitate
[none:29305] *** Process received signal ***
[none:29305] Signal: Bus error (7)
[none:29305] Signal code:  (128)
[none:29305] Failing at address: (nil)
```**
and 
 I check issue#10, and I comment out " glutInitContextVersion(3, 2)" in DeepMimic.py and Main.cpp. But error stills occurs.

How Do I modify the code ? Thank you very much.
