### ISSUE TITLE
Import Error Undefined symbol

### ISSUE THREAD

**Issue by Somedaywilldo** [xbpeng/DeepMimic#31]
After building, when run the Demo and came across this problem.
I'm using g++ on Ubuntu 16.04, I don't have the sudo privilege, so I install most of the dependencies manually. Don't know if this is the reason : (

Here is my error information:

$ python DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt

Traceback (most recent call last):
  File "DeepMimic.py", line 9, in <module>
    from env.deepmimic_env import DeepMimicEnv
  File "/h/jiaman/github/DeepMimic/env/deepmimic_env.py", line 3, in <module>
    from DeepMimicCore import DeepMimicCore
  File "/h/jiaman/github/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 28, in <module>
    _DeepMimicCore = swig_import_helper()
  File "/h/jiaman/github/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 24, in swig_import_helper
    _mod = imp.load_module('_DeepMimicCore', fp, pathname, description)
  File "/h/jiaman/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/h/jiaman/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)

ImportError: /h/jiaman/github/DeepMimic/DeepMimicCore/_DeepMimicCore.so: undefined symbol: _ZN11btMultiBody22addJointTorqueMultiDofEiPKf

**Comment by Somedaywilldo** [comment]
Although I can't fix this error, but I managed to run DeepMimic on a Ubuntu 16.04 with sudo privilege.

I think in the **DeepMimcCore/Makefile**, BULLET_INC_DIR is really confusing, I've tried serval ways but when running, I still get:

```
ImportError: libBulletDynamics.so.2.88 ..........
```
So inside bullet, I use make install to copy the libs to /usr dir, and modified the **.bashrc** file(LD_LIBRARY_PATH), and overcome this problem

```
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" #My eigen and bullet is here
```

**Comment by Somedaywilldo** [comment]
I will still be grateful if anyone knows why the error on the top of this page happened : )

**Comment by Somedaywilldo** [comment]
I've finally solve the issue, it is cause by the building process of bullet, when you use build_cmake_pybullet_double.sh inside the bullet3 source folder, remember to set "-DUSE_DOUBLE_PRECISION=ON" to " -DUSE_DOUBLE_PRECISION=OFF"

**Comment by asawaswapnil** [comment]
Hi @Somedaywilldo , could you please tell if you use your build_cmake_pybullet_double.sh inside the bullet3 src folder or inside parent folder bullet3-2.88? Also, which version of bullet did you use to not get this error of undefined symbol?
