### ISSUE TITLE
output result as a video

### ISSUE THREAD

**Issue by lyokka** [xbpeng/DeepMimic#32]
Is there any way to capture the animation result, and output it as a video

**Comment by lyokka** [comment]
I figure out how to output the animation, although I believe it is not the most efficient way. I use scripts like `frame = glReadPixels(x=0, y=0, width=win_width, height=win_height, format=GL_RGB, type=GL_FLOAT)` in function `animate`. However, I set `win_width` and `win_height` to 1:1, else it will cause problem(but I don't know why). Finally, I monitored the output frame, if output frame doesn't change, you can `shutdown()`

`
pre_frame = np.zeros((win_width, win_height))

def animate(callback_val):
    global prev_time
    global updates_per_sec
    global world
    global pre_frame

    counter_decay = 0

    if (animating):
        num_steps = get_num_timesteps()
        curr_time = get_curr_time()
        time_elapsed = curr_time - prev_time
        prev_time = curr_time

        timestep = -update_timestep if (playback_speed < 0) else update_timestep
        for i in range(num_steps):
            update_world(world, timestep)
        
        # FPS counting
        update_count = num_steps / (0.001 * time_elapsed)
        if (np.isfinite(update_count)):
            updates_per_sec = counter_decay * updates_per_sec + (1 - counter_decay) * update_count
            world.env.set_updates_per_sec(updates_per_sec)
            
        timer_step = calc_display_anim_time(num_steps)
        update_dur = get_curr_time() - curr_time
        timer_step -= update_dur
        timer_step = np.maximum(timer_step, 0)
        
        glutTimerFunc(int(timer_step), animate, 0)
        glutPostRedisplay()

        # get current frame
        curr_frame = glReadPixels(x = 0,
                           y = 0,
                           width = win_width,
                           height = win_height,
                           format = GL_RGB, 
                           type = GL_FLOAT)

        # generate frame name
        curr_frame_name = "some name"

        # save frame
        scipy.misc.imsave(curr_frame_name, cv2.flip(curr_frame, 0))

        # update previous frame
        if np.array_equal(pre_frame, curr_frame):
            print("VIDEO STOP")
            shutdown()

        pre_frame = curr_frame

    if (world.env.is_done()):
        print(" world.env.is_done() : " , world.env.is_done())
        shutdown()

    return
`

**Comment by xbpeng** [comment]
For recording the animation, we usually just run the visualizer with DeepMimic.py and record it using a screenrecorder. I think your approach should work as well.
