### ISSUE TITLE
ModuleNotFoundError: No module named '_DeepMimicCore'

### ISSUE THREAD

**Issue by bsivanantham** [xbpeng/DeepMimic#37]
Please help solve it 
```
Traceback (most recent call last):
  File "/home/balavivek/PycharmProjects/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/balavivek/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/balavivek/PycharmProjects/DeepMimic/DeepMimicCore/_DeepMimicCore.so: undefined symbol: _ZN11btMultiBody19setJointPosMultiDofEiPKf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepMimic.py", line 9, in <module>
    from env.deepmimic_env import DeepMimicEnv
  File "/home/balavivek/PycharmProjects/DeepMimic/env/deepmimic_env.py", line 3, in <module>
    from DeepMimicCore import DeepMimicCore
  File "/home/balavivek/PycharmProjects/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 17, in <module>
    _DeepMimicCore = swig_import_helper()
  File "/home/balavivek/PycharmProjects/DeepMimic/DeepMimicCore/DeepMimicCore.py", line 16, in swig_import_helper
    return importlib.import_module('_DeepMimicCore')
  File "/home/balavivek/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_DeepMimicCore'

```

**Comment by xbpeng** [comment]
Did you build the python wrappers for DeepMimicCore?

**Comment by SaturdayGenfo** [comment]
I have the exact same error. If the files _DeepMimicCore.so and DeepMimicCore.py are present, does that mean the wrappers were built properly ?

**Comment by bsivanantham** [comment]
python wrapper build ouput @xbpeng 

> `swig -c++ -python DeepMimicCore.i
clang++ -c -g -std=c++11 -O3 -Wall -fPIC  -I./ -I/usr/local/include/eigen3 -I/home/balavivek/PycharmProjects/DeepMimic/bullet3/src -lGLEW -lGL -lGLU -lglut -lBulletDynamics -lBulletCollision -lLinearMath -lm -lstdc++ DeepMimicCore.cpp DeepMimicCore_wrap.cxx -I/home/balavivek/anaconda3/include/python3.7m
clang: warning: -lGLEW: 'linker' input unused
clang: warning: -lGL: 'linker' input unused
clang: warning: -lGLU: 'linker' input unused
clang: warning: -lglut: 'linker' input unused
clang: warning: -lBulletDynamics: 'linker' input unused
clang: warning: -lBulletCollision: 'linker' input unused
clang: warning: -lLinearMath: 'linker' input unused
clang: warning: -lm: 'linker' input unused
clang: warning: -Z-reserved-lib-stdc++: 'linker' input unused
In file included from DeepMimicCore.cpp:3:
In file included from ./render/DrawUtil.h:6:
In file included from ./render/DrawMesh.h:21:
In file included from ./render/VertexBuffer.h:4:
./render/RenderState.h:87:44: warning: cast to 'void *' from smaller integer type 'unsigned int'
      [-Wint-to-void-pointer-cast]
                              mDataStride, (GLvoid *) mDataOffset);
                                           ^
In file included from DeepMimicCore.cpp:3:
In file included from ./render/DrawUtil.h:6:
In file included from ./render/DrawMesh.h:21:
./render/VertexBuffer.h:20:32: warning: field 'mRenderState' will be initialized after field 'mLocalData'
      [-Wreorder]
        cVertexBuffer():mRenderID(0), mRenderState(NULL), mLocalData(NULL),
                                      ^
./render/VertexBuffer.h:20:52: warning: field 'mLocalData' will be initialized after field 'mAttrInfo'
      [-Wreorder]
        cVertexBuffer():mRenderID(0), mRenderState(NULL), mLocalData(NULL),
                                                          ^
./render/VertexBuffer.h:21:15: warning: field 'mAttrInfo' will be initialized after field 'mNumAttr'
      [-Wreorder]
              mAttrInfo(NULL), mNumAttr(0), mSize(0)
              ^
./render/VertexBuffer.h:21:32: warning: field 'mNumAttr' will be initialized after field 'mSize' [-Wreorder]
              mAttrInfo(NULL), mNumAttr(0), mSize(0)
                               ^
./render/VertexBuffer.h:23:77: warning: field 'mRenderState' will be initialized after field 'mLocalData'
      [-Wreorder]
        cVertexBuffer(GLuint bufferID, cRenderState &r_state):mRenderID(bufferID), mRenderState(&r_st...
                                                                                   ^
./render/VertexBuffer.h:23:101: warning: field 'mLocalData' will be initialized after field 'mAttrInfo'
      [-Wreorder]
  ...bufferID, cRenderState &r_state):mRenderID(bufferID), mRenderState(&r_state), mLocalData(NULL),
                                                                                   ^
./render/VertexBuffer.h:24:40: warning: field 'mAttrInfo' will be initialized after field 'mNumAttr'
      [-Wreorder]
                                       mAttrInfo(NULL), mNumAttr(0), mSize(0)
                                       ^
./render/VertexBuffer.h:24:57: warning: field 'mNumAttr' will be initialized after field 'mSize' [-Wreorder]
                                       mAttrInfo(NULL), mNumAttr(0), mSize(0)
                                                        ^
./render/VertexBuffer.h:26:69: warning: field 'mRenderState' will be initialized after field 'mNumAttr'
      [-Wreorder]
        cVertexBuffer(const cVertexBuffer &old): mRenderID(old.mRenderID), mRenderState(old.mRenderSt...
                                                                           ^
./render/VertexBuffer.h:26:101: warning: field 'mNumAttr' will be initialized after field 'mSize' [-Wreorder]
  ...cVertexBuffer &old): mRenderID(old.mRenderID), mRenderState(old.mRenderState), mNumAttr(old.mNumAttr),
                                                                                    ^
In file included from DeepMimicCore.cpp:3:
In file included from ./render/DrawUtil.h:6:
In file included from ./render/DrawMesh.h:22:
./render/IBuffer.h:32:28: warning: field 'mRenderState' will be initialized after field 'mLocalData'
      [-Wreorder]
        cIBuffer(): mRenderID(0), mRenderState(NULL), mLocalData(NULL), mElemSize(0), mSize(0)
                                  ^
./render/IBuffer.h:32:48: warning: field 'mLocalData' will be initialized after field 'mElemSize' [-Wreorder]
        cIBuffer(): mRenderID(0), mRenderState(NULL), mLocalData(NULL), mElemSize(0), mSize(0)
                                                      ^
./render/IBuffer.h:32:66: warning: field 'mElemSize' will be initialized after field 'mSize' [-Wreorder]
        cIBuffer(): mRenderID(0), mRenderState(NULL), mLocalData(NULL), mElemSize(0), mSize(0)
                                                                        ^
./render/IBuffer.h:34:73: warning: field 'mRenderState' will be initialized after field 'mLocalData'
      [-Wreorder]
        cIBuffer(GLuint bufferID, cRenderState &r_state): mRenderID(bufferID), mRenderState(&r_state)...
                                                                               ^
./render/IBuffer.h:34:97: warning: field 'mLocalData' will be initialized after field 'mElemSize' [-Wreorder]
        cIBuffer(GLuint bufferID, cRenderState &r_state): mRenderID(bufferID), mRenderState(&r_state), mLocal...
                                                                                                       ^
./render/IBuffer.h:34:115: warning: field 'mElemSize' will be initialized after field 'mSize' [-Wreorder]
  ...cRenderState &r_state): mRenderID(bufferID), mRenderState(&r_state), mLocalData(NULL), mElemSize(0), ...
                                                                                            ^
17 warnings generated.
clang++ -shared -std=c++11 -O3 -Wall -fPIC  objs/Main.o objs/DeepMimicCore.o objs/util/IndexManager.o objs/util/Timer.o objs/util/Annealer.o objs/util/ArgParser.o objs/util/Trajectory.o objs/util/Rand.o objs/util/MathUtil.o objs/util/FileUtil.o objs/util/JsonUtil.o objs/util/BVHReader.o objs/util/json/json_value.o objs/util/json/json_reader.o objs/util/json/json_writer.o objs/anim/Shape.o objs/anim/KinTree.o objs/anim/Character.o objs/anim/KinCharacter.o objs/anim/Motion.o objs/sim/ExpPDController.o objs/sim/ImpPDController.o objs/sim/SimCharacter.o objs/sim/SimObj.o objs/sim/RBDUtil.o objs/sim/SimBox.o objs/sim/SpAlg.o objs/sim/CtVelController.o objs/sim/Controller.o objs/sim/CharController.o objs/sim/PerturbManager.o objs/sim/SimBodyLink.o objs/sim/GroundPlane.o objs/sim/CtCtrlUtil.o objs/sim/DeepMimicCharController.o objs/sim/SimCharBuilder.o objs/sim/CtController.o objs/sim/SimCapsule.o objs/sim/AgentRegistry.o objs/sim/SimSphere.o objs/sim/ObjTracer.o objs/sim/CtPDController.o objs/sim/SimPlane.o objs/sim/SimBodyJoint.o objs/sim/GroundBuilder.o objs/sim/World.o objs/sim/SimRigidBody.o objs/sim/Ground.o objs/sim/MultiBody.o objs/sim/ContactManager.o objs/sim/PDController.o objs/sim/SimJoint.o objs/sim/SimCylinder.o objs/sim/RBDModel.o objs/sim/CtrlBuilder.o objs/sim/SimCharGeneral.o objs/sim/Perturb.o objs/render/DrawUtil.o objs/render/DrawMesh.o objs/render/DrawPerturb.o objs/render/DrawWorld.o objs/render/GraphUtil.o objs/render/DrawCharacter.o objs/render/VertexBuffer.o objs/render/TextureDesc.o objs/render/Camera.o objs/render/DrawObj.o objs/render/TextureUtil.o objs/render/MeshUtil.o objs/render/DrawKinTree.o objs/render/IBuffer.o objs/render/Shader.o objs/render/DrawSimCharacter.o objs/render/ShadowMap.o objs/render/MatrixStack.o objs/render/DrawGround.o objs/render/lodepng/lodepng_util.o objs/render/lodepng/lodepng.o objs/scenes/DrawSceneSimChar.o objs/scenes/SceneImitate.o objs/scenes/Scene.o objs/scenes/RLSceneSimChar.o objs/scenes/DrawSceneKinChar.o objs/scenes/SceneSimChar.o objs/scenes/RLScene.o objs/scenes/SceneKinChar.o objs/scenes/DrawSceneImitate.o objs/scenes/DrawRLScene.o objs/scenes/DrawScene.o objs/scenes/SceneBuilder.o -lGLEW -lGL -lGLU -lglut -lBulletDynamics -lBulletCollision -lLinearMath -lm -lstdc++ DeepMimicCore_wrap.o -o _DeepMimicCore.so -L/home/balavivek/anaconda3/lib/ -lpython3.7m
`

**Comment by Fatiine** [comment]
@bsivanantham did you try to run that on mac? 
I had the same problem when I tried to run it on Mac. But I didn't find a solution yet. Did u ?

**Comment by bsivanantham** [comment]
@Fatiine  No I didn't try with mac .. I have been using Linux machine

**Comment by bsivanantham** [comment]
@xbpeng  hi can you please update me on this issue ...

**Comment by xbpeng** [comment]
From the error message, it seems to be a bullet issue from
undefined symbol: _ZN11btMultiBody19setJointPosMultiDofEiPKf
Maybe see if btMultiBody19setJointPosMultiDof is defined somewhere in your version of bullet? It could be a version issue with bullet. We are using Bullet 2.87, is that the version you are using?
