### ISSUE TITLE
CUDA enable

### ISSUE THREAD

**Issue by EnricoBeltramo** [xbpeng/DeepMimic#38]
I compiled this project on Windows 10, with python 3.5 and tensorflow gpu 1.12.0.
Tensorflow work  correctly with CUDA and GPU on my PC, but starting a train on this project seem the CUDA and GPU are disabled. There is a reason? Is it possible to enable it?

**Comment by xbpeng** [comment]
Our networks are fairly small, so they don't benefit as much from GPU accelerations, so for the most part we just train on the CPU. Also tensoflow-gpu doesn't play well with multiprocessing using MPI, and need some additional overhead to have multiple processes share a GPU.
