### ISSUE TITLE
Association rotation in motion file

### ISSUE THREAD

**Issue by EnricoBeltramo** [xbpeng/DeepMimic#42]
I have some issue to understand the association of rotations in motion file
Parsing the humanoid3d.txt model, starting from root till end i.e. for rigth  leg i have follow chain:

root --> rigth_hip --> rigth_knee --> rigth_ankle

appying the rotations / traslation of file, i have for that chain follow chain of transformations:
        root position (3D),
	root rotation (4D),
	right hip rotation (4D),
	right knee rotation (1D),
	right ankle rotation (4D),

My concern is that the latest one (right ankle rotation), haven't effect on any node position (because there is nothing connected to rigth_ankle). Did I miss something?

**Comment by xbpeng** [comment]
yes, the right ankle doesn't have any children joints connecting to it, but it does have a rigid body attached to the joint for the foot. The rigid bodies that are attached to the skeleton are defined in "BodyDefs" in the char files.
