### ISSUE TITLE
Training exception: test return increases explosively, while train return is quite small.

### ISSUE THREAD

**Issue by zhouzhq7** [xbpeng/DeepMimic#47]
![figure_1](https://user-images.githubusercontent.com/34722671/52984010-89fe6e80-3428-11e9-8cb5-e1984df79154.png)
As shown in the figure, as the training goes on about 8 hours, test return starts to increase explosively. At the same time, train return still increases quite steady, and test return becomes multiple times than train return. In about 12 hours, both test return and train return experience a sudden drop and become pretty close.
I see no difference between the code to calculate the train return and test return. Can you help to explain that? Appreciate that.

**Comment by xbpeng** [comment]
which motion is this? The reason why test_and train_return are different is because we test using a deterministic policy and train with a stochastic policy. The noise from the stochastic policy will make the train return lower than test return. I'm not sure why performance will sudden collapse though.

**Comment by zhouzhq7** [comment]
I see, thanks a lot. The motion is dribbling, created from CMU mocap data by my own. The character consists of 21 joints, and all of the joints are spherical, therefore the complexity is tripled. 

It seems that the training time increases linearly with the DoFs. The algorithm finally converges after training for 60 hours as shown in the following figure.
![figure_2](https://user-images.githubusercontent.com/34722671/53065303-17fc5700-3506-11e9-956f-f7215a9e7282.png)
