### ISSUE TITLE
How to extract the trajectory of the joint angle of the model

### ISSUE THREAD

**Issue by skylbc** [xbpeng/DeepMimic#56]
I would like to ask, after the model is trained, how to extract the joint angle,  can see the trajectory of the joint angle during the movement.thanks.

**Comment by xbpeng** [comment]
what do you mean by extract the joint angles? Do you mean record the motion produced by the simulation and export that into a file?

**Comment by skylbc** [comment]
Yes，I want to compare it with the reference data. Can you tell me?

**Comment by bracco-lab** [comment]
@skylbc I also I want to compare it with the reference data. Did you manage how?
