### ISSUE TITLE
Where can I find the code to kick and throw the ball to a fixed target?

### ISSUE THREAD

**Issue by shev0416** [xbpeng/DeepMimic#57]
Thank you for your code firstly @xbpeng .I could run the samples in the args folder now. 
The question is,I can't find the code to kick and throw the ball to a fixed target, I want to learn the code of these two examples, so that I can set my own goals to humanoid3d, so it could do things beyond the examples.

**Comment by xbpeng** [comment]
Sorry, but we've only included the code for imitation in this repo. You can probably modify the code to do what you want though.

**Comment by shev0416** [comment]
Thanks for your reply. I will try to modify the code:)
