### ISSUE TITLE
Training with multiple agents

### ISSUE THREAD

**Issue by jabolcni** [xbpeng/DeepMimic#62]
First, thank you for providing the DeepMimic source. Very interesting work. 

I have a question related to training with multiple agents. I might be wrong, but it seems to me that when training with multiple agents, training always runs only with one agent. How can I check with how many agents training is performed?

**Comment by xbpeng** [comment]
Sorry but the code only currently supports training one character at a time. It might take a fair bit of modification to support multiple characters.

**Comment by jabolcni** [comment]
Thanks for response, when I will have some time I will try to dig into code and see if I can make it work.

**Comment by BenJaminB1ue** [comment]
@jabolcni 你好，请问结果如何，咱们能交流一下吗？

**Comment by suryadwar** [comment]
@jabolcni were you able to find anything which can help us train multiple agents at once?
