### ISSUE TITLE
What's the use of DeepMimic.sln

### ISSUE THREAD

**Issue by Zju-George** [xbpeng/DeepMimic#69]
I know DeepMimicCore.sln is to build DeepMimicCore.py, but what is the use of DeepMimic.sln?

Also, do I have to set the path of OpenGL, GLEW, freeGlut when building DeepMimicCore.py?

Can Anybody help me, please, btw, I'm using windows10.

**Comment by ZhengyiLuo** [comment]
DeepMimicCore builds the core library, DeepMimic.sln builds the C++ environment that runs and renders, I think for debugging purpose. Yes, I think OpenGL, GLEW, freeGlut is necessary for python side, since you will need to render. If just training, then not.

**Comment by Zju-George** [comment]
@ZhengyiLuo 
thx, but could you please tell me where to define **PYTHON_INCLUDE** **SWIG_DIR**
![image](https://user-images.githubusercontent.com/33959089/61766983-5aa7bf80-ae15-11e9-8cf4-60150ba90a9e.png)
is it in the system Path or in Visual studio?

**Comment by Zju-George** [comment]
@ZhengyiLuo 然后我感觉你是个中国人，我就中文再问一下。。这个东西是在visual studio 里定义，还是系统的环境变量里定义啊。。。

**Comment by ZhengyiLuo** [comment]
在VS里面点击properties里面有include path你可以修改。具体的我不太记得了，我现在在用ubuntu develop所以。。。。。 

应该都可以。


From stackoverflow: 
```
You can set Visual Studio's global include path here:

Tools / Options / Projects and Solutions / VC++ Directories / Include files
```
