### ISSUE TITLE
Build error on Windows 10 (error LNK2001: unresolved external symbol)

### ISSUE THREAD

**Issue by donamin** [xbpeng/DeepMimic#75]
Hi

I'm getting these errors when building DeepMimicCore. I've already built and included bullet, OpenGL, and swig. Any idea what the problem is?

`1>GroundPlane.obj : error LNK2001: unresolved external symbol "public: __cdecl btStaticPlaneShape::btStaticPlaneShape(class btVector3 const &,float)" (??0btStaticPlaneShape@@QEAA@AEBVbtVector3@@M@Z)
1>MultiBody.obj : error LNK2001: unresolved external symbol "public: float const * __cdecl btMultiBody::getJointVelMultiDof(int)const " (?getJointVelMultiDof@btMultiBody@@QEBAPEBMH@Z)
1>MultiBody.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setupPlanar(int,float,class btVector3 const &,int,class btQuaternion const &,class btVector3 const &,class btVector3 const &,bool)" (?setupPlanar@btMultiBody@@QEAAXHMAEBVbtVector3@@HAEBVbtQuaternion@@00_N@Z)
1>MultiBody.obj : error LNK2001: unresolved external symbol "public: __cdecl btMultiBody::btMultiBody(int,float,class btVector3 const &,bool,bool,bool)" (??0btMultiBody@@QEAA@HMAEBVbtVector3@@_N11@Z)
1>SimBodyJoint.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::addJointTorqueMultiDof(int,float const *)" (?addJointTorqueMultiDof@btMultiBody@@QEAAXHPEBM@Z)
1>SimBodyJoint.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setJointVelMultiDof(int,float *)" (?setJointVelMultiDof@btMultiBody@@QEAAXHPEAM@Z)
1>SimBodyJoint.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setJointPosMultiDof(int,float *)" (?setJointPosMultiDof@btMultiBody@@QEAAXHPEAM@Z)
1>SimBodyJoint.obj : error LNK2001: unresolved external symbol "public: float * __cdecl btMultiBody::getJointPosMultiDof(int)" (?getJointPosMultiDof@btMultiBody@@QEAAPEAMH@Z)
1>SimBodyJoint.obj : error LNK2001: unresolved external symbol "public: float * __cdecl btMultiBody::getJointVelMultiDof(int)" (?getJointVelMultiDof@btMultiBody@@QEAAPEAMH@Z)
1>SimCharacter.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setupSpherical(int,float,class btVector3 const &,int,class btQuaternion const &,class btVector3 const &,class btVector3 const &,bool)" (?setupSpherical@btMultiBody@@QEAAXHMAEBVbtVector3@@HAEBVbtQuaternion@@00_N@Z)
1>SimCharacter.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setupRevolute(int,float,class btVector3 const &,int,class btQuaternion const &,class btVector3 const &,class btVector3 const &,class btVector3 const &,bool)" (?setupRevolute@btMultiBody@@QEAAXHMAEBVbtVector3@@HAEBVbtQuaternion@@000_N@Z)
1>SimCharacter.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setupPrismatic(int,float,class btVector3 const &,int,class btQuaternion const &,class btVector3 const &,class btVector3 const &,class btVector3 const &,bool)" (?setupPrismatic@btMultiBody@@QEAAXHMAEBVbtVector3@@HAEBVbtQuaternion@@000_N@Z)
1>SimCharacter.obj : error LNK2001: unresolved external symbol "public: void __cdecl btMultiBody::setupFixed(int,float,class btVector3 const &,int,class btQuaternion const &,class btVector3 const &,class btVector3 const &,bool)" (?setupFixed@btMultiBody@@QEAAXHMAEBVbtVector3@@HAEBVbtQuaternion@@00_N@Z)
1>SimCharacter.obj : error LNK2001: unresolved external symbol "public: __cdecl btMultiBodyJointLimitConstraint::btMultiBodyJointLimitConstraint(class btMultiBody *,int,float,float)" (??0btMultiBodyJointLimitConstraint@@QEAA@PEAVbtMultiBody@@HMM@Z)
1>SimJoint.obj : error LNK2001: unresolved external symbol "public: void __cdecl btAngularLimit::set(float,float,float,float,float)" (?set@btAngularLimit@@QEAAXMMMMM@Z)
1>SimJoint.obj : error LNK2001: unresolved external symbol "public: float __cdecl btHingeConstraint::getHingeAngle(void)" (?getHingeAngle@btHingeConstraint@@QEAAMXZ)
1>SimRigidBody.obj : error LNK2001: unresolved external symbol "public: void __cdecl btRigidBody::setDamping(float,float)" (?setDamping@btRigidBody@@QEAAXMM@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual float __cdecl btCollisionShape::getContactBreakingThreshold(float)const " (?getContactBreakingThreshold@btCollisionShape@@UEBAMM@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual float __cdecl btCollisionShape::getAngularMotionDisc(void)const " (?getAngularMotionDisc@btCollisionShape@@UEBAMXZ)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl btCollisionShape::getBoundingSphere(class btVector3 &,float &)const " (?getBoundingSphere@btCollisionShape@@UEBAXAEAVbtVector3@@AEAM@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl btSphereShape::calculateLocalInertia(float,class btVector3 &)const " (?calculateLocalInertia@btSphereShape@@UEBAXMAEAVbtVector3@@@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl btConvexShape::project(class btTransform const &,class btVector3 const &,float &,float &,class btVector3 &,class btVector3 &)const " (?project@btConvexShape@@UEBAXAEBVbtTransform@@AEBVbtVector3@@AEAM2AEAV3@3@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual float __cdecl btMultiBodyConstraintSolver::solveGroupCacheFriendlyFinish(class btCollisionObject * *,int,struct btContactSolverInfo const &)" (?solveGroupCacheFriendlyFinish@btMultiBodyConstraintSolver@@UEAAMPEAPEAVbtCollisionObject@@HAEBUbtContactSolverInfo@@@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: virtual float __cdecl btMultiBodyConstraintSolver::solveGroup(class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,struct btContactSolverInfo const &,class btIDebugDraw *,class btDispatcher *)" (?solveGroup@btMultiBodyConstraintSolver@@UEAAMPEAPEAVbtCollisionObject@@HPEAPEAVbtPersistentManifold@@HPEAPEAVbtTypedConstraint@@HAEBUbtContactSolverInfo@@PEAVbtIDebugDraw@@PEAVbtDispatcher@@@Z)
1>World.obj : error LNK2001: unresolved external symbol "protected: virtual float __cdecl btMultiBodyConstraintSolver::solveSingleIteration(int,class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,struct btContactSolverInfo const &,class btIDebugDraw *)" (?solveSingleIteration@btMultiBodyConstraintSolver@@MEAAMHPEAPEAVbtCollisionObject@@HPEAPEAVbtPersistentManifold@@HPEAPEAVbtTypedConstraint@@HAEBUbtContactSolverInfo@@PEAVbtIDebugDraw@@@Z)
1>World.obj : error LNK2001: unresolved external symbol "protected: virtual float __cdecl btMultiBodyConstraintSolver::solveGroupCacheFriendlySetup(class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,struct btContactSolverInfo const &,class btIDebugDraw *)" (?solveGroupCacheFriendlySetup@btMultiBodyConstraintSolver@@MEAAMPEAPEAVbtCollisionObject@@HPEAPEAVbtPersistentManifold@@HPEAPEAVbtTypedConstraint@@HAEBUbtContactSolverInfo@@PEAVbtIDebugDraw@@@Z)
1>World.obj : error LNK2001: unresolved external symbol "public: __cdecl btCapsuleShape::btCapsuleShape(float,float)" (??0btCapsuleShape@@QEAA@MM@Z)
1>World.obj : error LNK2001: unresolved external symbol "protected: virtual float __cdecl btSequentialImpulseConstraintSolver::solveGroupCacheFriendlyIterations(class btCollisionObject * *,int,class btPersistentManifold * *,int,class btTypedConstraint * *,int,struct btContactSolverInfo const &,class btIDebugDraw *)" (?solveGroupCacheFriendlyIterations@btSequentialImpulseConstraintSolver@@MEAAMPEAPEAVbtCollisionObject@@HPEAPEAVbtPersistentManifold@@HPEAPEAVbtTypedConstraint@@HAEBUbtContactSolverInfo@@PEAVbtIDebugDraw@@@Z)
1>E:\Aalto University\ProjectSources\DeepMimic\DeepMimicCore\_DeepMimicCore.pyd : fatal error LNK1120: 28 unresolved externals`

**Comment by xbpeng** [comment]
This looks like it might be having trouble locating the .lib files?

**Comment by Zju-George** [comment]
It is link error, which means you are not far away from **success**!
That's good news, but as the error suggests, I guess that's something about linking **bullet**, whick you should check first. 

Is **bullet** built successfully (released version/ x64 / unable double precision/ right version)? 

You can run  some bullet demos with the help of bullet documentation. See if you can run them.

**Comment by donamin** [comment]
Thanks for the quick reply.

I built Bullet 2.87 and the libraries are in bullet3\bin folder (I just had to remove '_vs2010_x64_release' postfix from the file names).

And yes I can run the demos.

**Comment by donamin** [comment]
> This looks like it might be having trouble locating the .lib files?

No it's not that. It is finding the lib files yet still producing the errors. I also used the off double precision flag when building bullet.

**Comment by Zju-George** [comment]
![image](https://user-images.githubusercontent.com/33959089/62915108-c4d4d400-bdc5-11e9-8a56-ecf2336449ec.png)
![image](https://user-images.githubusercontent.com/33959089/62915133-dd44ee80-bdc5-11e9-85d9-3d0d9b11563f.png)
![image](https://user-images.githubusercontent.com/33959089/62915138-e209a280-bdc5-11e9-8f73-a1779b356fb0.png)
See if these configuration helps any. Sorry I'm using Chinese Vistual studio, but they match correspondingly.

**Comment by donamin** [comment]
My bullet lib files are in bullet3\bin directory (and not bullet3\build_cmake\lib\release. Can this be the issue? But I'm able to run the test files.

**Comment by donamin** [comment]
> ![image](https://user-images.githubusercontent.com/33959089/62915108-c4d4d400-bdc5-11e9-8a56-ecf2336449ec.png)
> ![image](https://user-images.githubusercontent.com/33959089/62915133-dd44ee80-bdc5-11e9-85d9-3d0d9b11563f.png)
> ![image](https://user-images.githubusercontent.com/33959089/62915138-e209a280-bdc5-11e9-8f73-a1779b356fb0.png)
> See if these configuration helps any. Sorry I'm using Chinese Vistual studio, but they match correspondingly.

Can you put the whole of the address bar from the frist picture here? I can't read your third folder in the libs.

**Comment by Zju-George** [comment]
I think it might be the issue, you could run bullet demos because the .exe and .lib or .dll is in the same folder and .exe and find them.
And this is what inside the lib/Release 
![image](https://user-images.githubusercontent.com/33959089/62920570-c065e680-bdd8-11e9-92ed-7df63479fb25.png)
Here is whole sceen shot
![image](https://user-images.githubusercontent.com/33959089/62920621-e55a5980-bdd8-11e9-9eeb-c64864bfcae1.png)
![image](https://user-images.githubusercontent.com/33959089/62920643-f0ad8500-bdd8-11e9-9443-765db606810f.png)
![image](https://user-images.githubusercontent.com/33959089/62920657-f7d49300-bdd8-11e9-86d5-0cc6233c6856.png)

**Comment by Zju-George** [comment]
leave a comment if you find the problem😳

**Comment by donamin** [comment]
Voilla! It's solved. The problem was that I had to disable the double precision flag separately for BulletCollision, BulletDynamics, and LinearMath. So far I was disabling it only for the bullet master appbrowser project.
Thanks @Zju-George for the help :)

**Comment by vkozin97** [comment]
> Voilla! It's solved. The problem was that I had to disable the double precision flag separately for BulletCollision, BulletDynamics, and LinearMath. So far I was disabling it only for the bullet master appbrowser project.
> Thanks @Zju-George for the help :)

I am facing exactly the same issue: my Bullet lib files are stored in \bin folder with some odd prefixes, and the error list is similar to yours. Couldn't you please tell me where I should disable the double precision flag for BulletCollision, BulletDynamics and the LinearMath projects? The only place I mentioned such a flag was the CMakeLists.txt, where the flag was already disabled (in the OFF position)
![image](https://user-images.githubusercontent.com/15280666/63278527-168eca00-c2b0-11e9-91c1-da46be0a9f16.png)
Pre-thank you for any help!

**Comment by donamin** [comment]
> > Voilla! It's solved. The problem was that I had to disable the double precision flag separately for BulletCollision, BulletDynamics, and LinearMath. So far I was disabling it only for the bullet master appbrowser project.
> > Thanks @Zju-George for the help :)
> 
> I am facing exactly the same issue: my Bullet lib files are stored in \bin folder with some odd prefixes, and the error list is similar to yours. Couldn't you please tell me where I should disable the double precision flag for BulletCollision, BulletDynamics and the LinearMath projects? The only place I mentioned such a flag was the CMakeLists.txt, where the flag was already disabled (in the OFF position)
> ![image](https://user-images.githubusercontent.com/15280666/63278527-168eca00-c2b0-11e9-91c1-da46be0a9f16.png)
> Pre-thank you for any help!

I just removed the flag from the preprocessor definitions in the project properties (make sure that you're changing the properties of the correct project/configuration).
![image](https://user-images.githubusercontent.com/4231500/63293299-a4e95880-c27c-11e9-96ef-e4962c444687.png)

**Comment by vkozin97** [comment]
Seems like I finally solved my DoublePrecision trouble. In order to not manually remove the double-precision-flag in Preprocessor Definitions for every 62 projects, I
1) removed folders "\bin" and "\build3\vs2010",
2) checked that my CMakeLists.txt file has the USE_DOUBLE_PRECISION flag in OFF position,
3) in the build_visual_studio_vr_pybullet_double.bat file I deleted the "--double" option (that is the point I haven't done before, and I hardly believe that was the clue for me),
4) ran this .bat file
5) simply opened the 0_Bullet3Solution.sln and built it under "Release" and "x64" options.

It was successfully built, and after that my DeepMimicCore.sln wal successfully built as well and produced the so long awaited DeepMimicCore.py.

Thank everybody for help!

**Comment by pkxpp** [comment]
It's useful, thanks so much.
* modify three project: BulletDynamic BulletCollation and linearMath . property->C++->preprocessor, delete BT_USE_DOUBLE_PRECISION
* rebuild

**Comment by whisperzh** [comment]
> Seems like I finally solved my DoublePrecision trouble. In order to not manually remove the double-precision-flag in Preprocessor Definitions for every 62 projects, I
> 
> 1. removed folders "\bin" and "\build3\vs2010",
> 2. checked that my CMakeLists.txt file has the USE_DOUBLE_PRECISION flag in OFF position,
> 3. in the build_visual_studio_vr_pybullet_double.bat file I deleted the "--double" option (that is the point I haven't done before, and I hardly believe that was the clue for me),
> 4. ran this .bat file
> 5. simply opened the 0_Bullet3Solution.sln and built it under "Release" and "x64" options.
> 
> It was successfully built, and after that my DeepMimicCore.sln wal successfully built as well and produced the so long awaited DeepMimicCore.py.
> 
> Thank everybody for help!

But there are 3"--double" in the txt, should i delete all of the "--double"

**Comment by whisperzh** [comment]
hummm seems i have almost there and the visual studio told me:
1>LIBCMT.lib(exe_main.obj) : error LNK2001: 无法解析的外部符号 main
1>C:\Users\kevin\Downloads\whisperzh-DeepMimic-master\DeepMimic\DeepMimicCore\_DeepMimicCore.pyd : fatal error LNK1120: 1 个无法解析的外部命令
1>已完成生成项目“DeepMimicCore.vcxproj”的操作 - 失败。

And is there any solution to it?

**Comment by ahmetserdar** [comment]
hi, iam facing same problem with opencv, here is the problem. can anyone help me?
[image](https://user-images.githubusercontent.com/47100909/91013335-33ab5680-e5f0-11ea-9713-055e9f217a9f.png)

**Comment by xbpeng** [comment]
> hi, iam facing same problem with opencv, here is the problem. can anyone help me?
> [image](https://user-images.githubusercontent.com/47100909/91013335-33ab5680-e5f0-11ea-9713-055e9f217a9f.png)

There shouldn't be any dependencies on opencv. Do you know where the dependency is coming from?

**Comment by SpeedAss** [comment]
BT_THREADSAFE=1
BT_USE_DOUBLE_PRECISION
_DEBUG=1
Finally!! It's the issue

**Comment by ahmetserdar** [comment]
> > hi, iam facing same problem with opencv, here is the problem. can anyone help me?
> > [image](https://user-images.githubusercontent.com/47100909/91013335-33ab5680-e5f0-11ea-9713-055e9f217a9f.png)
> 
> There shouldn't be any dependencies on opencv. Do you know where the dependency is coming from?

Hello, i can not solve problem. So i forgot it:) This is the solution:)

**Comment by ahmetserdar** [comment]
> > hi, iam facing same problem with opencv, here is the problem. can anyone help me?
> > [image](https://user-images.githubusercontent.com/47100909/91013335-33ab5680-e5f0-11ea-9713-055e9f217a9f.png)
> 
> There shouldn't be any dependencies on opencv. Do you know where the dependency is coming from?

This problem is about Linker. Linker doesn't find  prebuilt library. Check your system path.
