### ISSUE TITLE
Concurrently display multiple characters?

### ISSUE THREAD

**Issue by xjwxjw** [xbpeng/DeepMimic#80]
Hello xuebin, I would like to ask one simple question:
I notice the DrawSceneSImChar.cpp is intended for multiple characters, right?
But it seems this part is not included in SceneBuilder.cpp.
So up to now is it possible to concurrently display multiple characters based on your code?

**Comment by xjwxjw** [comment]
With slight modification of DrawSceneKinChar.cpp and SceneKinChar.cpp/.h I managed to draw as following:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23734975/63662809-67437d00-c7f2-11e9-9516-b6814662c143.gif).
If someone has the same needs, here is the code just for reference:
[scenes.tar.gz](https://github.com/xbpeng/DeepMimic/files/3539300/scenes.tar.gz)

**Comment by xbpeng** [comment]
nice! We don't really support multiple characters at the moment. But looks like you've found a way to get it to work.

**Comment by Zju-George** [comment]
> With slight modification of DrawSceneKinChar.cpp and SceneKinChar.cpp/.h I managed to draw as following:
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23734975/63662809-67437d00-c7f2-11e9-9516-b6814662c143.gif).
> If someone has the same needs, here is the code just for reference:
> [scenes.tar.gz](https://github.com/xbpeng/DeepMimic/files/3539300/scenes.tar.gz)

Is it in the kinematic scene or simulation scene?

**Comment by xbpeng** [comment]
that looks like it's the kinematic scene
