### ISSUE TITLE
segmentation fault, doesnt print driver information 

### ISSUE THREAD

**Issue by asawaswapnil** [xbpeng/DeepMimic#88]
Facing the following error. And I don't have Nvidia on my system. Could this run on CPU or on Intel® UHD Graphics 620 (Kabylake GT2)? Could you please guide me how to go about it. Thanks

root@swapnil-Lenovo-ideapad-530S-15IKB:/home/swapnil/dg/DeepMimic# python3 DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt
[swapnil-Lenovo-ideapad-530S-15IKB:11231] *** Process received signal ***
[swapnil-Lenovo-ideapad-530S-15IKB:11231] Signal: Segmentation fault (11)
[swapnil-Lenovo-ideapad-530S-15IKB:11231] Signal code: Address not mapped (1)
[swapnil-Lenovo-ideapad-530S-15IKB:11231] Failing at address: 0x10
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f84d1629f20]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 1] /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0(_ZN11GlobalError11PushToStackEv+0x59)[0x7f84a1fb52a9]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 2] /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0(_Z13pkgInitConfigR13Configuration+0xf92)[0x7f84a2039082]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 3] /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so(+0x1a808)[0x7f84a22d6808]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 4] python3[0x5097cf]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 5] python3(_PyEval_EvalFrameDefault+0x449)[0x50b4a9]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 6] python3[0x507125]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 7] python3[0x5157d4]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 8] python3(PyCFunction_Call+0x13e)[0x56655e]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [ 9] python3(_PyEval_EvalFrameDefault+0x5682)[0x5106e2]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [10] python3[0x507125]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [11] python3[0x508fa0]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [12] python3[0x50999d]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [13] python3(_PyEval_EvalFrameDefault+0x449)[0x50b4a9]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [14] python3[0x508c69]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [15] python3[0x50999d]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [16] python3(_PyEval_EvalFrameDefault+0x449)[0x50b4a9]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [17] python3[0x508c69]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [18] python3[0x50999d]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [19] python3(_PyEval_EvalFrameDefault+0x449)[0x50b4a9]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [20] python3[0x508c69]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [21] python3[0x50999d]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [22] python3(_PyEval_EvalFrameDefault+0x449)[0x50b4a9]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [23] python3(_PyFunction_FastCallDict+0xf5)[0x508355]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [24] python3(_PyObject_FastCallDict+0x4f1)[0x5a4481]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [25] python3(_PyObject_CallMethodIdObjArgs+0xee)[0x5a54be]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [26] python3(PyImport_ImportModuleLevelObject+0x1ed)[0x4f622d]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [27] python3(_PyEval_EvalFrameDefault+0x22c6)[0x50d326]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [28] python3[0x507125]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] [29] python3[0x5157d4]
[swapnil-Lenovo-ideapad-530S-15IKB:11231] *** End of error message ***
Segmentation fault (core dumped)

**Comment by avi-grtl** [comment]
I was getting a similar error (but I was getting address 0x25) on my Mac (High Sierra, 10.13.6, latest nVidia drivers (387.x), everything installed from brew). I finally loaded it up on a linux install (18.04, nVidia 390.x, everything built from source) and it worked. I wasn't getting segfaults without the drivers installed, I was getting Bullet library errors. Something wasn't linking properly like this issue: #82. 

Not that this helps you, but it's interesting that you are also getting a seg fault error without nVidia drivers. I'm not smart enough to know what's happening, but maybe this info will help someone else. My best guess is that nVidia drivers bring something to the table.

**Comment by asawaswapnil** [comment]
Please let me know if you can use this code on Ubuntu 18.04 on CPU or on Intel® UHD Graphics 620 (Kabylake GT2)?

**Comment by asawaswapnil** [comment]
I found that I need Nvidia drivers for this. It needs GPU for simulation. The ideal solution would be if it can only run on the CPU completely. Please let me know if that can be possible.  Another possible way is to install Nvidea drivers on CPU and don't use Intel graphics but it's not an ideal solution because of not using intel graphics for everything.
