### ISSUE TITLE
freeglut (foo): failed to open display ' '

### ISSUE THREAD

**Issue by asawaswapnil** [xbpeng/DeepMimic#89]
error on running python3 DeepMimic.py --arg_file args/run_humanoid3d_spinkick_args.txt :

[[49574,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: ip-172-31-42-21

Another transport will be used instead, although this may result in
lower performance.

--------------------------------------------------------------------------

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

freeglut (foo): failed to open display ' '

Could you please guide on possible solution. I am running it on AWS p2.xlarge.

**Comment by asawaswapnil** [comment]
That was simply because AWS doesn't have a display. I changed the computer and it worked.

**Comment by hanziyu123** [comment]
Because you use the headless servers.
