### ISSUE TITLE
some question about deepmimic architecture

### ISSUE THREAD

**Issue by asawaswapnil** [xbpeng/DeepMimic#91]
I have a few doubts about states and action spaces. It would be great if you could clarify those. Where is the state and action size computed? humanoid has 34 dof but the actionsize of 36 and statesize of 197. Please help me understand these numbers. and also let me know a way to change them as I may need to remove a few items from the state and experiment.

**Comment by xbpeng** [comment]
The state features are using maximum coordinates, so there are more features than dof. You can find the code for computing the state features here:
https://github.com/xbpeng/DeepMimic/blob/ea26c3f2c35fb271d8bfefd53fd49397547c514d/DeepMimicCore/sim/DeepMimicCharController.cpp#L156
For the actions, target angles for spherical joints are represented as quaternion with 4 components. So the number of action parameters can end up being more than the number of dofs. Here's a link to the code for applying actions:
https://github.com/xbpeng/DeepMimic/blob/ea26c3f2c35fb271d8bfefd53fd49397547c514d/DeepMimicCore/sim/CtPDController.cpp#L78
